/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiInsightsRouteImport } from './routes/ai-insights'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DataExchangeRouteImport } from './routes/data-exchange'
import { Route as DataSharingPolicyRouteImport } from './routes/data-sharing-policy'
import { Route as EquipmentRouteImport } from './routes/equipment'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as MapRouteImport } from './routes/map'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as MyResourcesRouteImport } from './routes/my-resources'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RentalPolicyRouteImport } from './routes/rental-policy'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as BookingIdRouteImport } from './routes/booking.$id'
import { Route as ResourceIdRouteImport } from './routes/resource.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiInsightsRoute = AiInsightsRouteImport.update({
  id: '/ai-insights',
  path: '/ai-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DataExchangeRoute = DataExchangeRouteImport.update({
  id: '/data-exchange',
  path: '/data-exchange',
  getParentRoute: () => rootRouteImport,
} as any)
const DataSharingPolicyRoute = DataSharingPolicyRouteImport.update({
  id: '/data-sharing-policy',
  path: '/data-sharing-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentRoute = EquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const MyResourcesRoute = MyResourcesRouteImport.update({
  id: '/my-resources',
  path: '/my-resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalPolicyRoute = RentalPolicyRouteImport.update({
  id: '/rental-policy',
  path: '/rental-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingIdRoute = BookingIdRouteImport.update({
  id: '/booking/$id',
  path: '/booking/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourceIdRoute = ResourceIdRouteImport.update({
  id: '/resource/$id',
  path: '/resource/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-insights': typeof AiInsightsRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/data-exchange': typeof DataExchangeRoute
  '/data-sharing-policy': typeof DataSharingPolicyRoute
  '/equipment': typeof EquipmentRoute
  '/ledger': typeof LedgerRoute
  '/map': typeof MapRoute
  '/marketplace': typeof MarketplaceRoute
  '/my-resources': typeof MyResourcesRoute
  '/privacy': typeof PrivacyRoute
  '/rental-policy': typeof RentalPolicyRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/booking/$id': typeof BookingIdRoute
  '/resource/$id': typeof ResourceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-insights': typeof AiInsightsRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/data-exchange': typeof DataExchangeRoute
  '/data-sharing-policy': typeof DataSharingPolicyRoute
  '/equipment': typeof EquipmentRoute
  '/ledger': typeof LedgerRoute
  '/map': typeof MapRoute
  '/marketplace': typeof MarketplaceRoute
  '/my-resources': typeof MyResourcesRoute
  '/privacy': typeof PrivacyRoute
  '/rental-policy': typeof RentalPolicyRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/booking/$id': typeof BookingIdRoute
  '/resource/$id': typeof ResourceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-insights': typeof AiInsightsRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/data-exchange': typeof DataExchangeRoute
  '/data-sharing-policy': typeof DataSharingPolicyRoute
  '/equipment': typeof EquipmentRoute
  '/ledger': typeof LedgerRoute
  '/map': typeof MapRoute
  '/marketplace': typeof MarketplaceRoute
  '/my-resources': typeof MyResourcesRoute
  '/privacy': typeof PrivacyRoute
  '/rental-policy': typeof RentalPolicyRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/booking/$id': typeof BookingIdRoute
  '/resource/$id': typeof ResourceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-insights'
    | '/auth'
    | '/community'
    | '/dashboard'
    | '/data-exchange'
    | '/data-sharing-policy'
    | '/equipment'
    | '/ledger'
    | '/map'
    | '/marketplace'
    | '/my-resources'
    | '/privacy'
    | '/rental-policy'
    | '/settings'
    | '/support'
    | '/terms'
    | '/booking/$id'
    | '/resource/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-insights'
    | '/auth'
    | '/community'
    | '/dashboard'
    | '/data-exchange'
    | '/data-sharing-policy'
    | '/equipment'
    | '/ledger'
    | '/map'
    | '/marketplace'
    | '/my-resources'
    | '/privacy'
    | '/rental-policy'
    | '/settings'
    | '/support'
    | '/terms'
    | '/booking/$id'
    | '/resource/$id'
  id:
    | '__root__'
    | '/'
    | '/ai-insights'
    | '/auth'
    | '/community'
    | '/dashboard'
    | '/data-exchange'
    | '/data-sharing-policy'
    | '/equipment'
    | '/ledger'
    | '/map'
    | '/marketplace'
    | '/my-resources'
    | '/privacy'
    | '/rental-policy'
    | '/settings'
    | '/support'
    | '/terms'
    | '/booking/$id'
    | '/resource/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiInsightsRoute: typeof AiInsightsRoute
  AuthRoute: typeof AuthRoute
  CommunityRoute: typeof CommunityRoute
  DashboardRoute: typeof DashboardRoute
  DataExchangeRoute: typeof DataExchangeRoute
  DataSharingPolicyRoute: typeof DataSharingPolicyRoute
  EquipmentRoute: typeof EquipmentRoute
  LedgerRoute: typeof LedgerRoute
  MapRoute: typeof MapRoute
  MarketplaceRoute: typeof MarketplaceRoute
  MyResourcesRoute: typeof MyResourcesRoute
  PrivacyRoute: typeof PrivacyRoute
  RentalPolicyRoute: typeof RentalPolicyRoute
  SettingsRoute: typeof SettingsRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  BookingIdRoute: typeof BookingIdRoute
  ResourceIdRoute: typeof ResourceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-insights': {
      id: '/ai-insights'
      path: '/ai-insights'
      fullPath: '/ai-insights'
      preLoaderRoute: typeof AiInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-exchange': {
      id: '/data-exchange'
      path: '/data-exchange'
      fullPath: '/data-exchange'
      preLoaderRoute: typeof DataExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-sharing-policy': {
      id: '/data-sharing-policy'
      path: '/data-sharing-policy'
      fullPath: '/data-sharing-policy'
      preLoaderRoute: typeof DataSharingPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment': {
      id: '/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof EquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-resources': {
      id: '/my-resources'
      path: '/my-resources'
      fullPath: '/my-resources'
      preLoaderRoute: typeof MyResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rental-policy': {
      id: '/rental-policy'
      path: '/rental-policy'
      fullPath: '/rental-policy'
      preLoaderRoute: typeof RentalPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$id': {
      id: '/booking/$id'
      path: '/booking/$id'
      fullPath: '/booking/$id'
      preLoaderRoute: typeof BookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resource/$id': {
      id: '/resource/$id'
      path: '/resource/$id'
      fullPath: '/resource/$id'
      preLoaderRoute: typeof ResourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiInsightsRoute: AiInsightsRoute,
  AuthRoute: AuthRoute,
  CommunityRoute: CommunityRoute,
  DashboardRoute: DashboardRoute,
  DataExchangeRoute: DataExchangeRoute,
  DataSharingPolicyRoute: DataSharingPolicyRoute,
  EquipmentRoute: EquipmentRoute,
  LedgerRoute: LedgerRoute,
  MapRoute: MapRoute,
  MarketplaceRoute: MarketplaceRoute,
  MyResourcesRoute: MyResourcesRoute,
  PrivacyRoute: PrivacyRoute,
  RentalPolicyRoute: RentalPolicyRoute,
  SettingsRoute: SettingsRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  BookingIdRoute: BookingIdRoute,
  ResourceIdRoute: ResourceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
